version: '3.6'

services:
  apitest:
    container_name: apitest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/root
    healthcheck:
      disable: true
    restart: unless-stopped
    ports:
      - 8080:8080
    tty: true

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: arantzafrontend
      MONGO_INITDB_ROOT_PASSWORD: Z5j9mgETSaY0iFM4
      MONGO_INITDB_DATABASE: testMongo
