version: '3.6'

services:
  testmongodb:
    container_name: testmongodb
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/root
    healthcheck:
      disable: true
    restart: unless-stopped
    ports:
      - 8080:8080
    tty: true
  mongotest:
    image: mongo:latest
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: arantzafrontend
      MONGO_INITDB_ROOT_PASSWORD: Z5j9mgETSaY0iFM4
      MONGO_INITDB_DATABASE: testMongo
